### ISSUE TITLE
Documentation: Does this work on MacOS version ...?

### ISSUE THREAD

**Issue by boxleytw** [thoughtworks/dancing-glyphs#3]
Does this work on MacOS 10 (latest non-Big Sur)?

For corporate reasons, I cannot at this time upgrade to Big Sur, and would enjoy the glypies as my screen saver when at work.

**Comment by erikdtw** [comment]
Maybe a documentation issue. The readme says "El Capitan or newer", which is still correct, but that's hidden in the tech section.
